---
- name: ensure modprobe tool is installed
  package:
    name: "{{ hardening_filesystem_package }}"
    state: present
  become: true

- name: creating blacklist for old and vulnerable filesystems
  template:
    src: etc/modprobe.d/blacklist_filesystems.conf.j2
    dest: /etc/modprobe.d/blacklist_filesystems.conf
    owner: root
    group: root
    mode: 0640
  become: true
