---
- name: create system wide crypto policy config
  template:
    src: etc/crypto-policies/config.j2
    dest: /etc/crypto-policies/config
    owner: root
    group: root
    mode: 0644
  register: __hardening_crypto_config
  notify: reboot system
