---
- name: ensure System.map files are only accessible by root
  block:
    - name: find System.map files
      find:
        paths: /boot
        pattern: "*System.map*"
      register: __found_system_map_files

    - name: reset permissions of System.map files
      file:
        path: "{{ item.path }}"
        owner: root
        group: root
        mode: 0600
      loop: "{{ __found_system_map_files.files }}"
      when: __found_system_map_files.files | length > 0

- name: ensure no world writable files exists
  block:
    - name: find world writable files
      shell:
        cmd: 'find / -type f -perm /o=w -print -o \( -path /dev -or -path /sys -or -path /proc -or -path {{ (__hardening_file_perms_bin_dirs | list + hardening_file_perms_extra_bin_dirs | list ) | join(" -or -path ") }} \) -prune'
      register: __found_world_writeable_files
      changed_when: false
      ignore_errors: true

    - name: remove world writable flag from files
      stat:
        path: "{{ item }}"
        mode: o-w
        state: file
      loop: "{{ __found_world_writeable_files.stdout_lines }}"


- name: find files in bin directories with group or other write permissions
  shell:
    cmd: "find -L {{ (__hardening_file_perms_bin_dirs | list + hardening_file_perms_extra_bin_dirs | list) | join(' ') }} -type f -perm /go+w"
  register: __found_group_other_write_bin_files
  changed_when: false
  ignore_errors: true

- name: unset group and others write permission in bin directories
  file:
    path: "{{ item }}"
    mode: go-w
    state: file
  loop: "{{ __found_group_other_write_bin_files.stdout_lines }}"

- name: ensure shadow permissions
  file:
    path: /etc/shadow
    owner: "{{ hardening_file_perms_shadow.user }}"
    group: "{{ hardening_file_perms_shadow.group }}"
    mode: "{{ hardening_file_perms_shadow.mode }}"

- name: ensure passwd permissions
  file:
    path: /etc/passwd
    owner: "{{ hardening_file_perms_passwd.user }}"
    group: "{{ hardening_file_perms_passwd.group }}"
    mode: "{{ hardening_file_perms_passwd.mode }}"

- name: change su perms to only be accessible by root
  file:
    path: /bin/su
    owner: root
    group: root
    mode: 0750
