---
- name: find files with group write permissions
  shell:
    cmd: "find -L {{ (__hardening_file_perms_bin_dirs | list + hardening_file_perms_extra_bin_dirs | list) | join(' ') }} -type f -perm /go+w"
  register: found_files
  changed_when: false
  ignore_errors: true

- name: unset group and others write permission
  file:
    path: "{{ item }}"
    mode: go-w
    state: file
  with_items:
    - "{{ found_files.stdout_lines }}"

- name: ensure shadow permissions
  file:
    path: /etc/shadow
    owner: "{{ hardening_file_perms_shadow.user }}"
    group: "{{ hardening_file_perms_shadow.group }}"
    mode: "{{ hardening_file_perms_shadow.mode }}"

- name: ensure passwd permissions
  file:
    path: /etc/passwd
    owner: "{{ hardening_file_perms_passwd.user }}"
    group: "{{ hardening_file_perms_passwd.group }}"
    mode: "{{ hardening_file_perms_passwd.mode }}"

- name: change su perms to only be accessible by root
  file:
    path: /bin/su
    owner: root
    group: root
    mode: 0750
