---
- name: ensure limits.d directory exists
  file:
    owner: root
    group: root
    mode: 0755
    path: /etc/security/limits.d
    state: directory
  notify: reboot system

- name: set limits
  pam_limits:
    comment: "{{ item.comment }}"
    dest: "{{ __hardening_limits_conf_file }}"
    domain: "{{ item.domain }}"
    limit_item: "{{ item.limit_item }}"
    limit_type: "{{ item.limit_type }}"
    value: "{{ item.value }}"
  loop: "{{ __hardening_limits_conf }}"
  notify: reboot system
