---
- name: configure login.defs
  template:
    src: login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644
  become: true

- name: set umask for login shells
  replace:
    owner: root
    group: root
    mode: 0644
    path: /etc/profile
    regexp: '([ \t])(umask)([ \t])\d{3,4}'
    replace: '\1umask {{ hardening_system_umask }}'
