---
- name: configure login.defs
  template:
    src: etc/login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644

- name: configure useradd defaults
  template:
    src: etc/default/useradd.j2
    dest: /etc/default/useradd
    owner: root
    group: root
    mode: 0644

- name: configure hardening features in profile.d
  template:
    src: etc/profile.d/hardening.sh.j2
    dest: /etc/profile.d/hardening.sh
    owner: root
    group: root
    mode: 0644

- name: set umask for init.d functions
  replace:
    owner: root
    group: root
    mode: 0644
    path: /etc/init.d/functions
    regexp: '(^[^ \t])*(umask)([ \t])*\d{3,4}'
    replace: '\1umask {{ hardening_login_umask }}'
  when: ansible_os_family == "RedHat"

- name: delete issue.net
  file:
    path: /etc/issue.net
    state: absent

- name: remove all files from update-motd.d
  file:
    path: /etc/update-motd.d
    state: absent

- name: configure /etc/motd and /etc/issue
  template:
    src: "etc/{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - issue
    - motd
