---
- name: configure login.defs
  template:
    src: etc/login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644
  become: true

- name: set umask for login shells
  replace:
    owner: root
    group: root
    mode: 0644
    path: /etc/profile
    regexp: '([ \t])*(umask)([ \t])*\d{3,4}'
    replace: '\1umask {{ hardening_system_umask }}'

- name: setting auto-logout time
  lineinfile:
    line: "TMOUT=600"
    path: /etc/profile
    state: present

- name: set umask for init.d functions
  replace:
    owner: root
    group: root
    mode: 0644
    path: /etc/init.d/functions
    regexp: '([ \t])*(umask)([ \t])*\d{3,4}'
    replace: '\1umask {{ hardening_system_umask }}'
  when: ansible_os_family == "RedHat"
