---
- name: configure login.defs
  template:
    src: etc/login.defs.j2
    dest: /etc/login.defs
    owner: root
    group: root
    mode: 0644
  become: true

- name: configure /etc/motd and /etc/issue
  template:
    src: etc/issue_motd.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0644
  loop:
    - /etc/issue
    - /etc/motd

- name: configure hardening features in profile.d
  template:
    src: etc/profile.d/hardening.sh.j2
    dest: /etc/profile.d/hardening.sh
    owner: root
    group: root
    mode: 0644
  become: true

- name: set umask for init.d functions
  replace:
    owner: root
    group: root
    mode: 0644
    path: /etc/init.d/functions
    regexp: '(^[^ \t])*(umask)([ \t])*\d{3,4}'
    replace: '\1umask {{ hardening_system_umask }}'
  when: ansible_os_family == "RedHat"
  become: true
