---
- name: import preflight.yml
  import_tasks: preflight.yml
  tags:
    - always

- name: include os dependent variable file
  include_vars: "{{ item }}"
  with_first_found:
    files:
      - "{{ ansible_os_family | lower }}.yml"
    skip: true
  tags:
    - always

- name: import pam.yml
  import_tasks: pam.yml
  become: true
  when: hardening_enable_pam_configuration | bool
  tags:
    - hardening_pam

- name: import login_defs.yml
  import_tasks: login_defs.yml
  become: true
  when: hardening_enable_login_defs_configuration | bool
  tags:
    - hardening_login_defs

- name: import limits.yml
  import_tasks: limits.yml
  become: true
  when: hardening_enable_limits_configuration | bool
  tags:
    - hardening_limits

- name: import file_permissions.yml
  import_tasks: file_permissions.yml
  become: true
  when: hardening_enable_file_perms_configuration | bool
  tags:
    - hardening_file_permissions

# - name: import user.yml
#   import_tasks: user.yml
#   become: true
#   when: hardening_enable_user_configuration | bool
#   tags:
#     - hardening_user
