---
- name: import preflight.yml
  import_tasks: preflight.yml
  tags:
    - always

- name: include os dependent variable file
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      skip: true
  tags:
    - always

- name: import pam.yml
  import_tasks: pam.yml
  when: hardening_pam | bool
  become: true
  tags:
    - hardening_pam

- name: import login.yml
  import_tasks: login.yml
  when: hardening_login | bool
  become: true
  tags:
    - hardening_login

- name: import limits.yml
  import_tasks: limits.yml
  when: hardening_limits | bool
  become: true
  tags:
    - hardening_limits

- name: import sysctl.yml
  import_tasks: sysctl.yml
  when: hardening_sysctl | bool
  become: true
  tags:
    - hardening_sysctl

- name: import file_permissions.yml
  import_tasks: file_permissions.yml
  when: hardening_file_perms | bool
  become: true
  tags:
    - hardening_file_permissions

- name: import mount_filesystems.yml
  import_tasks: mount_filesystems.yml
  when: hardening_mount_filesystems | bool
  become: true
  tags:
    - hardening_mount_filesystems

- name: import crypto_policy.yml
  import_tasks: crypto_policy.yml
  become: true
  when:
    - hardening_crypto_policy | bool
    - ansible_os_family == "RedHat"
  tags:
    - hardening_crypto_policy

- name: import services.yml
  import_tasks: services.yml
  become: true
  when:
    - hardening_services | bool
  tags:
    - hardening_services

- name: import yum.yml
  import_tasks: yum.yml
  become: true
  when:
    - hardening_yum | bool
    - ansible_os_family == "RedHat"
  tags:
    - hardening_yum

- name: import network.yml
  import_tasks: network.yml
  become: true
  when:
    - hardening_network | bool
  tags:
    - hardening_network

# - name: import user.yml
#   import_tasks: user.yml
#   become: true
#   when: hardening_enable_user_configuration | bool
#   tags:
#     - hardening_user
