---
- name: ensure modprobe tool is installed
  package:
    name: "{{ hardening_mount_filesystems_packages }}"
    state: present

- name: bind mountpoints
  block:
    - name: secure /home mount
      mount:
        src: /home
        path: /home
        opts: bind,defaults,nosuid,nodev
        fstype: none
        state: present
      when: hardening_mount_secure_home | bool

    - name: secure /boot mount
      mount:
        src: /boot
        path: /boot
        opts: bind,defaults,nosuid,nodev
        fstype: none
        state: present
      when: hardening_mount_secure_boot | bool

    - name: secure /var mount
      mount:
        src: /var
        path: /var
        opts: bind,defaults,nodev
        fstype: none
        state: present
      when: hardening_mount_secure_var | bool

    - name: secure /var/tmp mount
      mount:
        src: /var/tmp
        path: /var/tmp
        opts: bind,defaults,nosuid,nodev,noexec
        fstype: none
        state: present
      when: hardening_mount_secure_var_tmp | bool

    - name: secure /var/log mount
      mount:
        src: /var/log
        path: /var/log
        opts: bind,defaults,nosuid,nodev,noexec
        fstype: none
        state: present
      when: hardening_mount_secure_var_log | bool

- name: tmpfs mountpoints
  block:
    - name: create /tmp mount in memmory
      mount:
        fstype: tmpfs
        opts: "rw,nosuid,nodev,noexec,relatime,size=25%,mode=1777"
        src: tmpfs
        path: /tmp
        state: present

    - name: create /dev/shm fstab entry
      mount:
        fstype: tmpfs
        opts: "rw,nosuid,nodev,noexec"
        src: tmpfs
        path: /dev/shm
        state: present
  when: hardening_mount_secure_tmpfs | bool


- name: creating blacklist for old and vulnerable filesystems
  template:
    src: etc/modprobe.d/blacklist_filesystems.conf.j2
    dest: /etc/modprobe.d/blacklist_filesystems.conf
    owner: root
    group: root
    mode: 0640
  notify: reboot system
