---
- name: disable NetworkManger resolv.conf management
  ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - option: dns
      value: none
    - option: rc-managed
      value: unmanaged
  when:
    - (hardening_network_search_bases | length > 0 or hardening_network_dns_servers | length > 0)
    - ansible_os_family == "RedHat"
  notify: restart NetworkManager

- name: disable dhclient autoupdate resolv.conf
  copy:
    content: "make_resolv_conf() { :; }"
    dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsautoupdate
    owner: root
    group: root
    mode: 0755
  when:
    - (hardening_network_search_bases | length > 0  or hardening_network_dns_servers | length > 0)
    - ansible_os_family == "Debian"

- name: configure resolve.conf dns servers
  template:
    src: etc/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: (hardening_network_search_bases | length > 0  or hardening_network_dns_servers | length > 0)

- name: disable zeroconf configuration
  lineinfile:
    path: /etc/sysconfig/network
    line: "NOZEROCONF=yes"
    state: present
  when: ansible_os_family == "RedHat"

- name: blacklist uncommon network protocols
  template:
    src: etc/modprobe.d/blacklist_net_protocols.conf.j2
    dest: /etc/modprobe.d/blacklist_net_protocols.conf
    owner: root
    group: root
    mode: 0640
