---
- name: configure systemd
  block:
    - name: ensure systemd  configuration directories exists
      file:
        owner: root
        group: root
        mode: 0755
        path: "{{ item }}"
        state: directory
      loop:
        - /etc/systemd/system.conf.d
        - /etc/systemd/coredump.conf.d

    - name: configure systemd daemon
      template:
        src: etc/systemd/system.conf.d/hardening.conf.j2
        dest: /etc/systemd/system.conf.d/hardening.conf
        owner: root
        group: root
        mode: 0644

    - name: configure systemd coredump
      template:
        src: etc/systemd/coredump.conf.d/hardening.conf.j2
        dest: /etc/systemd/coredump.conf.d/hardening.conf
        owner: root
        group: root
        mode: 0644

- name: configure system services
  block:
    - name: disable and mask unwanted services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
        masked: yes
      loop: "{{ hardening_blacklist_services | difference(hardening_whitelist_services) }}"
      when: item in ansible_facts.services
