---
- name: install sysctl package
  package:
    name: "{{ hardening_syctl_package }}"
    state: present

- name: ensure certain kernel parameters are set
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: "{{ hardening_sysctl_conf }}"
    state: present
  loop: "{{ hardening_sysctl_kernel_parameters }}"
  notify: reboot system
