---
- name: create administrator group
  group:
    name: "{{ hardening_user_admin_group }}"
    state: present
    gid: 10000

- name: create administrativ user
  user:
    name: "{{ hardening_user_admin_user }}"
    comment: Administrativ User
    group: "{{ hardening_user_admin_group }}"
    uid: 10000
    password: "{{ hardening_user_admin_password }}"

- name: copy publickey to administrativ users home dir
  authorized_key:
    user: "{{ hardening_user_admin_user }}"
    key: "{{ item }}"
  when:
    - hardening_user_admin_user_ssh_pub_keys is defined
    - hardening_user_admin_user_ssh_pub_keys | length > 0
  loop: "{{ hardening_user_admin_user_ssh_pub_keys }}"

- name: allow sudo for admins group
  template:
    src: etc/sudoers.d/admins.j2
    dest: /etc/sudoers.d/admins
    owner: root
    group: root
    mode: 0600
