---
- name: restart NetworkManager
  systemd:
    name: NetworkManager.service
    state: restarted
  become: true

- name: reboot system
  reboot:
  when:
    - ansible_virtualization_type | lower != "docker"
    - hardening_allow_reboot | bool
  become: true
