---
- name: restart NetworkManager
  systemd:
    name: NetworkManager.service
    state: restarted
  become: true
  when: "'NetworkManager.service' in ansible_facts.services"

- name: reboot system
  reboot:
  when: ansible_virtualization_type | lower != "docker"
  become: true
