---
- name: Converge
  hosts: all
  remote_user: ansible
  debugger: on_failed
  roles:
    - role: ansible-role-hardening
  vars:
    hardening_login_sulog_file: "no"
    hardening_login_env_paths:
      - ~/bin
      - ~/.bin
    hardening_network_dns_servers:
      - 1.1.1.1
      - 1.0.0.1
    hardening_network_dns_search_bases:
      - localdomain
    hardening_user_admin_password: "$6$HbiLuAG.qArODKOD$pBeMm0wjfscVWG55e3iUiB5omf7hognkkk7BGFUodY6tVlTIhNIF9l2sU7kgs04BamTKm2QCgqn31QR59qSYq1"
