---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: yamllint
platforms:
  - name: hardeningcentos8
    box: centos/8
    box_version: 1905.1
    memory: 4096
    cpus: 4
    provision: True
  - name: hardeningdebian10
    box: debian/buster64
    box_version: 10.3.0
    memory: 4096
    cpus: 4
    provision: True
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  lint:
    name: ansible-lint
verifier:
  name: ansible
  lint:
    name: flake8
