---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint
platforms:
  - name: hardening_centos8
    image: registry.gitlab.com/dvonessen/docker-ansible-nonroot-centos:8
    pre_build_image: true
  - name: hardening_debian10
    image: registry.gitlab.com/dvonessen/docker-ansible-nonroot-debian:10
    pre_build_image: true
  - name: hardening_ubuntu1804
    image: registry.gitlab.com/dvonessen/docker-ansible-nonroot-ubuntu:18.04
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
