---
- name: Converge
  hosts: all
  remote_user: ansible
  debugger: on_failed
  roles:
    - role: ansible-role-hardening
  vars:
    hardening_login_defs_sulog_file: no
    hardening_login_defs_env_paths:
      - ~/bin
      - ~/.bin
    hardening_pam_fail_delay: 5000000
    hardening_pam_failed_logins: 5
